[package]
name = "rust_relm_and_camera_practice"
version = "0.1.0"
authors = ["asuki <asukiaaa@gmail.com>"]

[dependencies]
gtk = "^0.3.0"
gdk-pixbuf = "0.3.0"
relm = "^0.11.0"
relm-derive = "^0.11.0"
rscam = "0.5.3"
